server:
  port: 8083
spring:
  data:
    mongodb:
      host: localhost
      name: embeded_db
  application:
    name: cloud-product-catalog
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka/