server:
  port: 8084
spring:
  application:
    name: cloud-product-order
  data:
    mongodb:
      host: localhost
      name: embeded_db
logging:
  level:
    org:
      nipu: DEBUG
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka/